### Create Educator
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "taylor"
}

### Get Student List
GET http://localhost:8080/student?size=2&page=1

### Get Student
GET http://localhost:8080/student/2

### Get Lecture of student
GET http://localhost:8080/student/1/lectures?semester=SPRING_2024